name: twicon
description: Icons for Tiawan
version: 0.1.0
homepage: https://github.com/zonble/twicon

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: 'Taiwan icon'
      fonts:
        - asset: packages/twicon/fonts/twicon.otf
